index.html
Initial html file, close issue #1
=> Created basic html structure (issue #1)

index.html, styles.css
navbar looks clean and works well
=> fixed navbar code

index.html
added an iframe leading to a youtube video of notetaker
=> added video iframe to demonstrate usage of notetaker

index.html
added example.com hyperlinks (terms, privacy, support) in the sign up section
=> added three new hyperlinks

signup.html
Link back to the main page after signing up in signup.html.
=> fix #25: Linked main landing page with signup button

signup.html
Fixed submit button, close #27
=> Reworked submit button (Issue #27)

signup.html
Added comments to the signup box
=> Added relevant comments

index.html, styles.css
Close #39 with this, updated iframe to have sign-up page
=> Updated iframe content (Issue #39)

index.html, styles.css
=> added image (Issue #41)

styles.css
=> moved image (Issue #41)

README.md, index.html
=> added comments throughout code

index.html
=> added image back (Issue #47)

backend/signin.php, backend/signup.php, index.html, signin.html, signup.html, styles.css
- Externalized and standardized CSS styles for signin and signup forms.
- Added JavaScript functionality to dynamically load forms into iframe.
- Updated backend redirection logic after successful signup.
- Improved user experience by preventing iframe page breaks upon form submission.
=> Implement dynamic signin/signup iframe switching and CSS improvements

backend/signin.php
fixed the redirect on the iframe to dashboard.php
=> fixed redirect to dashboard.php

backend/dashboard.php, index.html
added the dashboard to the navbar and added a redirect to signin page on index.html if not signed in
=> added dashboard to navbar

index.html
just added smooth scrolling so the anchor actually works
=> fixed anchor scroll behavior

backend/dashboard.php
Added a button to the dashboard page that will end ('destroy') the user's session and return them to the landing page.
=> Add logout functionality to dashboard page, fixes #78

backend/dashboard.php, backend/note.php, backend/signup.php
Also threw in a potential fix to redirecting user to dashboard when signing up -- if they are already signed up. But this is not fully completed.
=> Added feature to delete notes, fixes #81

backend/dashboard.php
Close #85, this allows users to see (but not edit or delete) other users' notes
=> updated note view (Issue #85)

backend/index.php
Close #107 updating index.php to include note endpoints
=> Updated index to include note endpoints (Issue #107)

backend/Model/NoteModel.php
Also add parameter validation (if needed, not sure). I assume controller file can cover this, but felt it is better safe than sorry.
=> Added note update function

backend/Controller/Api/NoteController.php, backend/Model/NoteModel.php
=> updated NoteController and small changes to NoteModel

backend/Controller/Api/NoteController.php, backend/Model/NoteModel.php
=> Added endpoint to get one note by id (Issue #122)

backend/Controller/Api/NoteController.php
fixed the message to say "Note created successfully"
=> fix: fixed note create message

backend/index.php
fixed the sql data from being leaked
=> fix: stopped sql data leakage

backend/Controller/Api/UserController.php, backend/Model/UserModel.php, frontend/mobile/App.js, frontend/mobile/api.js, frontend/mobile/pages/Login.js, frontend/mobile/pages/NoteForm.js, frontend/mobile/pages/NotesView.js, frontend/mobile/pages/Signup.js, frontend/mobile/pages/homepage.js
added login and signup functionality on the mobile frontend
=> feat: added login and signup functionality

backend/dashboard.php
cleaned up the dashboard ui to make it look more modern and not so.. bleh
=> fix: clean up ui dashboard

backend/Controller/Api/UserController.php, backend/Model/UserModel.php, backend/dashboard.php, backend/leaderboard.php
Integrated leaderboard functionality with UserModel and UserController. It looks fine (could be more spiced up) but works overall!
=> Added leaderboard page (Issue #143)

backend/composer.json, backend/composer.lock, backend/phpunit.xml, backend/tests/UserApiTest.php
add unit testing for the application
=> add unit testing for notetaker-ai

backend/composer.json, backend/composer.lock, backend/dashboard.php
..
add markdown functionality to notetaker-ai
=> added markdown functionality

backend/Model/NoteModel.php, backend/dashboard.php
sort by descending order for notes
=> sorted by descending for user convenience

README.md, backend/create_category.php, backend/dashboard.php, backend/note.php
add new categories to notes and the ability to view them through "notebooks"
=> feat: add new category and textbook functionality

backend/Model/NoteModel.php, backend/dashboard.php, backend/note.php, styles.css
=> fixed note editing stuff and added markdown back

backend/Controller/Api/AIController.php, backend/Model/AIModel.php, backend/dashboard.php
more ai functionality, summarization, bullet points, etc
=> added more AI functionality
